//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
//
// On Thu Jul 31 12:54:52 CST 2025
//
//
// Ports:
// Name                         I/O  size props
// fn_add                         O    64
// fn_add_op1                     I    64
// fn_add_op2                     I    64
// fn_add_sub                     I     1
//
// Combinational paths from inputs to outputs:
//   (fn_add_op1, fn_add_op2, fn_add_sub) -> fn_add
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_fn_add(fn_add_op1,
		     fn_add_op2,
		     fn_add_sub,
		     fn_add);
  // value method fn_add
  input  [63 : 0] fn_add_op1;
  input  [63 : 0] fn_add_op2;
  input  fn_add_sub;
  output [63 : 0] fn_add;

  // signals for module outputs
  wire [63 : 0] fn_add;

  // remaining internal signals
  wire [64 : 0] inv_op2__h23, x__h25;

  // value method fn_add
  assign fn_add = x__h25[64:1] ;

  // remaining internal signals
  assign inv_op2__h23 = { fn_add_op2 ^ {64{fn_add_sub}}, fn_add_sub } ;
  assign x__h25 = { fn_add_op1, 1'b1 } + inv_op2__h23 ;
endmodule  // module_fn_add

