//
// Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
//
// On Thu Jul 31 12:54:52 CST 2025
//
//
// Ports:
// Name                         I/O  size props
// fn_decode_rs3                  O     5
// fn_decode_rs3_inst             I    32
//
// Combinational paths from inputs to outputs:
//   fn_decode_rs3_inst -> fn_decode_rs3
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_fn_decode_rs3(fn_decode_rs3_inst,
			    fn_decode_rs3);
  // value method fn_decode_rs3
  input  [31 : 0] fn_decode_rs3_inst;
  output [4 : 0] fn_decode_rs3;

  // signals for module outputs
  wire [4 : 0] fn_decode_rs3;

  // value method fn_decode_rs3
  assign fn_decode_rs3 =
	     (fn_decode_rs3_inst[6:4] == 3'b100 &&
	      fn_decode_rs3_inst[1:0] == 2'b11) ?
	       fn_decode_rs3_inst[31:27] :
	       5'd0 ;
endmodule  // module_fn_decode_rs3

